### ISSUE TITLE
Apache Kafka support

### ISSUE THREAD

**Issue by puttareddy** [runabol/piper#12]
Hi,

It looks like the current implementation supports jms, rabbitmq. Do you have any future roadmap to integrate with Apache Kafka as the message broker?

**Comment by runabol** [comment]
not yet but if enough users find it useful it might be a good addition.

**Comment by puttareddy** [comment]
Thanks..!

**Comment by ccamel** [comment]
@creactiviti Is there any progress on this one ? :smiley:
