### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by ccamel** [runabol/piper#24]
I started working on [MongoDB](https://www.mongodb.com) database support in `Piper`. I think it's a very interesting NoSQL database for `Piper` due to its ability to persist very easily JSON (/BSON) documents.

I would like to know if you would be interested in this contribution?

**Comment by runabol** [comment]
Interesting. Have you considered Postgres JSON support? In fact, I kind of regret not taking advantage of it when I first designed Piper.

**Comment by ccamel** [comment]
@creactiviti Yes I have. This is the first remark I made to myself when I looked at the database schemas. 
I think we could easily implement it in Piper. Perhaps we can open an issue about this?

**Comment by runabol** [comment]
Absolutely
