### ISSUE TITLE
Your first pipeline example does not work

### ISSUE THREAD

**Issue by anshumanr** [runabol/piper#32]
So i am following the steps as mentioned at [https://github.com/creactiviti/piper#writing-your-first-pipeline](https://github.com/creactiviti/piper#writing-your-first-pipeline) & get an error -

> /piper$ curl -s -X POST -H Content-Type:application/json -d '{"pipelineId":"mypipeline","inputs":{"name":"Arik"}}' http://localhost:8080/jobs
{"timestamp":"2019-03-21T20:57:15.006+0000","status":400,"error":"Bad Request","exception":"java.lang.IllegalArgumentException","message":"Unknown pipeline: mypipeline","path":"/jobs"}

I have tried this with the `mypipeline.yaml`  in 

> /piper$ ll src/main/resources/pipelines/
total 1
drwxrwxrwx 1 xxx xxx 256 Mar 21 16:53 ./
drwxrwxrwx 1 xxx xxx   0 Mar 21 16:24 ../
drwxrwxrwx 1 xxx xxx   0 Mar 21 16:24 demo/
-rwxrwxrwx 1 xxx xxx 240 Mar 21 16:45 mypipeline.yaml*

and at 

> /piper$ ll piper/pipelines/
total 1
drwxrwxrwx 1 xxx xxx 160 Mar 21 16:45 ./
drwxrwxrwx 1 xxx xxx 152 Mar 21 16:49 ../
-rwxrwxrwx 1 xxx xxx 240 Mar 21 16:45 mypipeline.yaml*

to the same error.

Where should this yaml file go?

**Comment by ccamel** [comment]
@anshumanr 
It works if you put the `mypipeline.yaml` file under `~/piper/pipelines` (sub-folder of your home directory).

**Comment by anshumanr** [comment]
Thanks. That worked (i feel stupid).
