### ISSUE TITLE
Pipeline task

### ISSUE THREAD

**Issue by vascofg** [runabol/piper#4]
Is it possible to call other pipelines by their "pipelineId" as Tasks from another pipeline, and pass them parameters?

**Comment by runabol** [comment]
Not yet. but definitely on the road map. I'll take a look tonight.

**Comment by runabol** [comment]
The primitives are there. Pipelines already have the notion of `inputs` and `outputs` at a pipeline level. So I imagine something like starting a sub-workflow and using its output as the output of that task. Also probably creating a new `TaskDispatcher` implementation is how I would want to implement it.

**Comment by runabol** [comment]
@vascofg far from complete but I started working on it: https://github.com/creactiviti/piper/tree/subflows

**Comment by vascofg** [comment]
looking great!

**Comment by runabol** [comment]
I merged the changes. Feel free to try it out and provide feedback
