### ISSUE TITLE
How to get more then 20 items in jobs list

### ISSUE THREAD

**Issue by deskjet482** [runabol/piper#47]
Hi

When i run:
curl http://localhost:8080/jobs | jq . 

I get a list of  the last 20 jobs but i have 71 jobs.
It says i have 4 pages worth.
how can i get the next page?

Cheers,
Alex

**Comment by ccamel** [comment]
Hi @deskjet482 

According to [JobsController](https://github.com/creactiviti/piper/blob/master/src/main/java/com/creactiviti/piper/web/JobsController.java#L51) implementation, you should be able to set the page with the query parameter `p` (starting from 1), like that:

```sh
curl "http://localhost:8080/jobs?p=2" | jq .
```

**Comment by deskjet482** [comment]
Thanks
