### ISSUE TITLE
Docker setup help, Failed to obtain JDBC Connection

### ISSUE THREAD

**Issue by yevon** [runabol/piper#49]
I've reached this amazing project and I want to give it a try, but I'm unable to setup the enviroment with docker. I've tried two tutorials without success. If I follow the docker instructions at the end of this repository, I just end up with this message if I perform a get request to the /jobs url:

![image](https://user-images.githubusercontent.com/121157/81612105-90d22200-93dc-11ea-871b-0a95cf684588.png)

The same if I make a POST request with postman, same message:

![image](https://user-images.githubusercontent.com/121157/81612268-d8f14480-93dc-11ea-9501-2983d49cbd01.png)

My docker-compose config looks like this:

    rabbit:
      image: creactiviti/rabbitmq:3.7.7-management
      hostname: rabbit
      ports:
        - 15672:15672
        - 5672:5672
      restart: always

    postgres:
      image: postgres:11
      ports: 
        - 5432:5432
      environment:
        - POSTGRES_DB=piper
        - POSTGRES_USER=piper
        - POSTGRES_PASSWORD=piper

    coordinator:
      image: creactiviti/piper:latest
      ports:
        - 8080:8080
      environment:
        - piper.worker.enabled=true
        - piper.coordinator.enabled=true
        - piper.worker.subscriptions.tasks=1
        - piper.pipeline-repository.filesystem.enabled=true
        - piper.pipeline-repository.filesystem.location-pattern=/app/pipelines/**/*.yaml
        - spring.datasource.initialize=true
        - spring.datasource.name=piper
        - spring.datasource.platform=postgres
        - spring.datasource.url=jdbc:postgresql://localhost:5432/piper
        - spring.datasource.username=piper
        - spring.datasource.password=piper
      volumes:
        - D:/test/docker/piper/pipelines:/app/pipelines
      restart: always

I also tried above setup but without any of the spring options, as the docker tutorial in this repository states with same results.

I have some questions:

1. Is it mandatory having a DB for following the hello world tutorial?
2. Is there any other tutorial might I follow?
3. Is it compatible with Oracle, or just h2 and postgres?

I also tried this tutorial without success, I think I'm missing some steps.
https://medium.com/@arik.cohen/transcoding-video-at-scale-with-piper-dca23eb26fd2

Thanks for your work!

**Comment by yevon** [comment]
Fixed, responding myself:

spring.datasource.url was not correct, actually it wasn't localhost, it was postgresql://postgres:5432/piper

1. Yes, postgres seems mandatory. Database initialization was also failing, so I executed database table script manually.

**Comment by runabol** [comment]
@yevon sorry for the late reply. Just saw this. Glad you got it to work!
