### ISSUE TITLE
Job.status webhooks don't notify of STARTED status

### ISSUE THREAD

**Issue by vascofg** [runabol/piper#8]
I've started using Webhooks (thanks a lot for the updated documentation btw) but have encountered the following issue:
I get notified of `CREATED` and `COMPLETED` events, but not of `STARTED` ones.
I believe there is a bug on this [line](https://github.com/creactiviti/piper/blob/d9ad142b3f67960f13edc315e940f8f27c8e81aa/piper-core/src/main/java/com/creactiviti/piper/core/Coordinator.java#L110), which publishes the event before changing the status. Is this it or am I understanding incorrectly?
Also the notification of the `CREATED` status seems unnecessary, we already get it on the response to the create job request.

**Comment by runabol** [comment]
Yes, that totally looks like a silly bug. 

On the `CREATED` though it might be useful if you want to notify a 3rd party application.

**Comment by vascofg** [comment]
d5be235a4d5eaab4739ba54ed46ccc4559bfdcf7 fixed it, thanks!
